#pragma once
// Auto-generated by BixHeaderTool. Do not modify.

#include "Bix/Reflection/BixReflection.h"

namespace Bix::Reflection::detail { inline constexpr int BIX_INTERNAL_GENERATED_BODY_BASELINE = __COUNTER__; }
#if defined(GENERATED_BODY)
#undef GENERATED_BODY
#endif
#define BIX_INTERNAL_GENERATED_BODY_SELECT_IMPL(index) BIX_INTERNAL_GENERATED_BODY_CASE_##index
#define BIX_INTERNAL_GENERATED_BODY_SELECT(index) BIX_INTERNAL_GENERATED_BODY_SELECT_IMPL(index)
#define GENERATED_BODY() BIX_INTERNAL_GENERATED_BODY_SELECT(__COUNTER__ - ::Bix::Reflection::detail::BIX_INTERNAL_GENERATED_BODY_BASELINE - 1)()

#define BIX_INTERNAL_GENERATED_BODY_CASE_0() \
public: \
    static ::Bix::Reflection::ClassInfo& StaticClass() \
    { \
        using ThisClass = ::BixEngine::Game::TestScene; \
        const ::Bix::Reflection::ClassInfo* superClass = nullptr; \
        superClass = &::BixEngine::Game::Scene::StaticClass(); \
        auto& classInfo = ::Bix::Reflection::detail::RegisterClass<ThisClass>( \
            "TestScene", \
            "BixEngine::Game::TestScene", \
            superClass, \
            [](::Bix::Reflection::ClassInfo& classInfo) \
            { \
                (void)classInfo; \
            }); \
        return classInfo; \
    } \
    virtual ::Bix::Reflection::ClassInfo& GetClass() const \
    { \
        return StaticClass(); \
    } \
private: \
    static inline ::Bix::Reflection::detail::ClassRegistrationInvoker<::BixEngine::Game::TestScene> __BixReflection_AutoRegister{};

