#include "HeaderGenerator.h"
#include "Parser/TokenUtils.h"
#include "Parser/HeaderParser.h"
#include <sstream>
#include <iostream>

namespace BixTool
{
    std::string GenerateHeader(const std::filesystem::path& headerPath, const HeaderParseResult& result)
    {
        if (!result.ContainsReflection)
            return {};

        std::ostringstream oss;
        oss << "#pragma once\n";
        oss << "// Auto-generated by BixHeaderTool. Do not modify.\n\n";
        oss << "#include \"Bix/Reflection/BixReflection.h\"\n\n";
        oss << "#ifdef GENERATED_BODY\n";
        oss << "#undef GENERATED_BODY\n";
        oss << "#endif\n\n";

        if (result.Classes.empty()) {
            oss << "#define GENERATED_BODY(...) static_assert(false, \"No reflected class found.\")\n";
            return oss.str();
        }

        const ParsedClass& cls = result.Classes.front();
        const std::string qualified = MakeQualifiedName(cls.Namespaces, cls.Name);
        const std::string scoped    = MakeScopedName(cls.Namespaces, cls.Name);

        std::string baseScoped;
        if (!baseScoped.empty()) 
        {
            baseScoped = Trim(cls.BaseType);

            if (!baseScoped.empty() && baseScoped.find("::") == std::string::npos) 
            {
                baseScoped = MakeScopedName(cls.Namespaces, baseScoped);
            } else if (baseScoped.rfind("::", 0) != 0) 
            {
                baseScoped = "::" + baseScoped;
            }
        }

        oss << "#define GENERATED_BODY() \\\n";
        oss << "public: \\\n";
        oss << "    static ::Bix::Reflection::ClassInfo& StaticClass() \\\n";
        oss << "    { \\\n";
        oss << "        using ThisClass = " << scoped << "; \\\n";
        oss << "        ::Bix::Reflection::ClassInfo* superClass = nullptr; \\\n";
        if (!baseScoped.empty())
            oss << "        superClass = &" << baseScoped << "::StaticClass(); \\\n";
        oss << "        auto& classInfo = ::Bix::Reflection::detail::RegisterClass<ThisClass>( \\\n";
        oss << "            \"" << cls.Name << "\", \\\n";
        oss << "            \"" << qualified << "\", \\\n";
        oss << "            superClass, \\\n";
        oss << "            [](::Bix::Reflection::ClassInfo& info) \\\n";
        oss << "            { \\\n";
        if (cls.Properties.empty()) {
            oss << "                (void)info; \\\n";
        } else {
            for (const Property& property : cls.Properties)
                oss << "                ::Bix::Reflection::detail::RegisterProperty<ThisClass, "
                    << property.Type << ">(info, \"" << property.Name << "\", &ThisClass::"
                    << property.Name << ", \"" << property.Type << "\"); \\\n";
        }
        oss << "            }); \\\n";
        oss << "        return classInfo; \\\n";
        oss << "    } \\\n";
        oss << "    virtual ::Bix::Reflection::ClassInfo& GetClass() const { return StaticClass(); } \\\n";
        oss << "private: \\\n";
        oss << "    static inline ::Bix::Reflection::detail::ClassRegistrationInvoker<" << scoped
            << "> __BixReflection_AutoRegister{};\n";

        return oss.str();
    }
}