#include "HeaderGenerator.h"
#include "Parser/TokenUtils.h"
#include "Parser/HeaderParser.h"
#include <sstream>
#include <iostream>

namespace BixTool
{
    std::string GenerateHeader(const std::filesystem::path& headerPath, const HeaderParseResult& result)
    {
        if (!result.ContainsReflection)
            return {};

        std::ostringstream oss;
        oss << "#pragma once\n";
        oss << "// Auto-generated by BixHeaderTool. Do not modify.\n\n";
        oss << "#include \"Reflection/BixReflection.h\"\n\n";
        oss << "#ifdef GENERATED_BODY\n";
        oss << "#undef GENERATED_BODY\n";
        oss << "#endif\n\n";

        if (result.Classes.empty())
        {
            oss << "#define GENERATED_BODY(...) static_assert(false, \"No reflected class found.\")\n";
            return oss.str();
        }

        const ParsedClass& cls = result.Classes.front();
        const std::string qualified = MakeQualifiedName(cls.Namespaces, cls.Name);
        const std::string scoped    = MakeScopedName(cls.Namespaces, cls.Name);

        std::string baseScoped = Trim(cls.BaseType);
        if (!baseScoped.empty())
        {
            if (baseScoped.find("::") == std::string::npos)
                baseScoped = MakeScopedName(cls.Namespaces, baseScoped);
            else if (baseScoped.rfind("::", 0) != 0)
                baseScoped = "::" + baseScoped;
        }

        // --------------------------
        // Begin macro generation
        // --------------------------
        oss << "#define GENERATED_BODY() \\\n";
        oss << "public: \\\n";
        oss << "    static ::Bix::Reflection::ClassInfo& StaticClass() \\\n";
        oss << "    { \\\n";
        oss << "        using ThisClass = " << scoped << "; \\\n";
        oss << "        ::Bix::Reflection::ClassInfo* superClass = nullptr; \\\n";
        if (!baseScoped.empty())
            oss << "        superClass = &" << baseScoped << "::StaticClass(); \\\n";
        oss << "        auto& classInfo = ::Bix::Reflection::detail::RegisterReflectedClass<ThisClass>( \\\n";
        oss << "            \"" << cls.Name << "\", \\\n";
        oss << "            \"" << qualified << "\", \\\n";
        oss << "            superClass, \\\n";
        oss << "            [](::Bix::Reflection::ClassInfo& info) \\\n";
        oss << "            { \\\n";

        // --------------------------
        // Properties
        // --------------------------
        if (cls.Properties.empty())
        {
            oss << "                (void)info; \\\n";
        }
        else
        {
            for (const Property& property : cls.Properties)
            {
                oss << "                ::Bix::Reflection::detail::RegisterProperty<ThisClass, "
                    << property.Type << ">(info, \"" << property.Name << "\", &ThisClass::"
                    << property.Name << ", \"" << property.Type << "\"); \\\n";
            }
        }

        // --------------------------
        // Constructor logic (conditional generation)
        // --------------------------
        oss << "                if constexpr (std::is_abstract_v<ThisClass>) \\\n";
        oss << "                { info.ConstructorFn = nullptr; } \\\n";

        // ✅ Génération conditionnelle selon la hiérarchie détectée
        if (cls.BaseType == "Component")
        {
            oss << "                else \\\n";
            oss << "                { \\\n";
            oss << "                    /* Component: construction liée à un Actor */ \\\n";
            oss << "                    info.ConstructorFn = +[](void* context) -> void* \\\n";
            oss << "                    { \\\n";
            oss << "                        auto* owner = static_cast<::BixEngine::Game::Actor*>(context); \\\n";
            oss << "                        if (!owner) return nullptr; \\\n";
            oss << "                        if constexpr (std::is_constructible_v<ThisClass, ::BixEngine::Game::Actor*>) \\\n";
            oss << "                            return static_cast<void*>(new ThisClass(owner)); \\\n";
            oss << "                        else if constexpr (std::is_default_constructible_v<ThisClass>) \\\n";
            oss << "                            return static_cast<void*>(new ThisClass()); \\\n";
            oss << "                        else return nullptr; \\\n";
            oss << "                    }; \\\n";
            oss << "                } \\\n";
        }
        else if (cls.BaseType == "Actor")
        {
            oss << "                else \\\n";
            oss << "                { \\\n";
            oss << "                    /* Actor: simple construction par défaut */ \\\n";
            oss << "                    if constexpr (std::is_default_constructible_v<ThisClass>) \\\n";
            oss << "                        info.ConstructorFn = +[](void*) -> void* { return static_cast<void*>(new ThisClass()); }; \\\n";
            oss << "                    else info.ConstructorFn = nullptr; \\\n";
            oss << "                } \\\n";
        }
        else if (cls.BaseType == "Object" || baseScoped.find("Object") != std::string::npos)
        {
            oss << "                else \\\n";
            oss << "                { \\\n";
            oss << "                    /* Object: construction simple */ \\\n";
            oss << "                    if constexpr (std::is_default_constructible_v<ThisClass>) \\\n";
            oss << "                        info.ConstructorFn = +[](void*) -> void* { return static_cast<void*>(new ThisClass()); }; \\\n";
            oss << "                    else info.ConstructorFn = nullptr; \\\n";
            oss << "                } \\\n";
        }
        else
        {
            oss << "                else \\\n";
            oss << "                { \\\n";
            oss << "                    /* Type externe ou non géré */ \\\n";
            oss << "                    info.ConstructorFn = nullptr; \\\n";
            oss << "                } \\\n";
        }

        // --------------------------
        // End lambda & registration
        // --------------------------
        oss << "            }); \\\n";
        oss << "        return classInfo; \\\n";
        oss << "    } \\\n";
        oss << "    virtual ::Bix::Reflection::ClassInfo& GetClass() const { return StaticClass(); } \\\n";
        oss << "private: \\\n";
        oss << "    static inline ::Bix::Reflection::detail::ClassRegistrationInvoker<" << scoped
            << "> __BixReflection_AutoRegister{};\n";

        return oss.str();
    }
}
